version: "3"
networks:
  snocode_default:
    external: true
services:
  codejs:
    image: ghcr.io/snomiao/code-js
    build: .
    environment:
      VSCODE_SERVER_PORT: 80
    volumes:
      - ./home:/home/
      - ./:/code-js/
    networks:
      - snocode_default