version: "3"
services:
  code:
    build: .
    environment:
      PORT: 2314
    volumes:
      - ./home:/root/
      - ./home:/root/.gitconfig
      - ./:/code-js/
    ports:
      - 127.0.0.1:2314:2314
