version: "3"
networks:
  snocode_default:
    external: true
services:
  code-js:
    build: .
    environment:
      VSCODE_SERVER_PORT: 80
    volumes:
      - ./home:/root/
      - ./:/code-js/
    networks:
      - snocode_default